spring:
  application:
    name: todo-service
    
  datasource:
    url: jdbc:mysql://database-1.co6w7xankpqz.us-east-1.rds.amazonaws.com:3306/hr
    username: arun
    password: arun1234
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true